### ISSUE TITLE
Is strip_silence_sox.py used for 3.1.4?

### ISSUE THREAD

**Issue by daisukelab** [SarthakYadav/GISE-51-pytorch#1]
Hi,
First, thank you for sharing the GISE-51 and this repository.
I have a question about the strip_silence_sox.py, was it used for the post-processing "... were added after manually clipping silence"?

> 3.1.4. Silence Filtering
> "The utterances outright rejected by sox were manually inspected, and if incorrectly rejected, were added after manually clipping silence."

P.S. I'm also wondering how I can pronounce "GISE" -- is it like "guys"? :)

**Comment by SarthakYadav** [comment]
Hi @daisukelab 

Thanks for your interest.
Yes, that's what strip_silence_sox is used for. We actually ran this script on a copy of the dataset, and very few instances were added back where the script didn't work correctly.

> P.S. I'm also wondering how I can pronounce "GISE" -- is it like "guys"? :)

Ahh, call it whatever feels right to you. I pronounce it like gee-say, but something like "guys" would be fine too :D

**Comment by daisukelab** [comment]
Hi @SarthakYadav,
Thanks for your answers, and the efforts you've made for the gee-say 51! ;)
